### PR TITLE
DMs no longer include @users in the message

### PR DESCRIPTION
**Pull request by johnathan-rodriguez**

### CODE REVIEW

**Review by wrp801 — APPROVED** [review]

**Comment by johnathan-rodriguez** [comment]
I think it is unnecessary. Change was pretty straightforward and [https://int.shipyardapp.io/Shipyard%20Blueprint%20Library/projects/a9a77a34-3fd0-4180-[…]bec1-9d33192b8d0c/logs/380e3e0a-24f2-4ce9-a156-dea1cbd754c0](https://int.shipyardapp.io/Shipyard%20Blueprint%20Library/projects/a9a77a34-3fd0-4180-9a87-5d50d6e379d6/fleets/35f2b4a0-c1bb-49c4-bec1-9d33192b8d0c/logs/380e3e0a-24f2-4ce9-a156-dea1cbd754c0)
worked successfully with the caveat that it didn't @ you in the slack channel but I believe that is because you are no longer a member of the channel

**Comment by wrp801** [comment]
The code is approved, you can change the version in this PR

**Comment by wrp801** [comment]
Okay, then if Jon is not going to QA you can bump the version out of pre-release now

**Comment by johnathan-rodriguez** [comment]
to be on the safe side mind jumping back in [int_slack_blueprint channel](https://slack.com/archives/#C06JPRDFZ0U) for one last test

**Pull request merged**
