### PR TITLE
Wes/integ 35 deploy

### PR DESCRIPTION
**Pull request by wrp801**
Fixed an error discovered in QA for the upload

### CODE REVIEW

**Review by johnathan-rodriguez — APPROVED** [review]

**Comment by wrp801** [comment]
Going to take it out of prerelease now that it has passed QA

**Comment by johnathan-rodriguez** [comment]
oh and update- i will be taking tomorrow off and depending on how jons qa goes ill either take friday off or a half day

**Comment by johnathan-rodriguez** [comment]
GCS is handed off to him and tableau and mode should be ready for deployment as well. I think i need to make a fresh account for tableau tho.

**Comment by johnathan-rodriguez** [comment]
that makes only google sheets left on my end which shouldn't be released this week anyways so that we don't too many new blueprints out

**Pull request merged**
